name: publish
on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"

env:
  GITHUB_TOKEN: ${{ secrets.WRITE_PACKAGES }}

jobs:
  publish:
    runs-on: self-hosted
    container:
      image: sbtscala/scala-sbt:eclipse-temurin-jammy-21.0.2_13_1.9.9_2.12.19
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: sbt publish
      run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        sbt clean publish
  gh-release:
    needs: [publish]
    runs-on: self-hosted
    steps:
    - uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.RAW_CI_PAT }}
        generate_release_notes: true
        draft: false
        prerelease: ${{ contains(github.ref_name, '-') }}
        tag_name: ${{ github.ref_name }}
